### ISSUE TITLE
船橋いつ行くの

### ISSUE THREAD

**Issue by clarinet758** [clarinet758/NewYearResolution#29]
これ要注意↓
https://togetter.com/li/2117555
意見調整時に「任意」という単語を使用しないでください。古語と現代語で反対の意味を持っていて意見調整が不能に陥ります
焼き鳥を串から外して細かく分けてレベルでの食べ物シェアみたいなのなるべく避けたいです
これ↑

いつ行くの？
2024年、金曜日とか休日前がいいかも

メインの食べ物
ホルモン焼きとかお店さんを探しているかもしれません
https://www.hotpepper.jp/strJ001224559/
が気になります

定休日や営業時間
わかりません

場所
船橋が都合いいかも

服装
礼装以外

特定の日にキャンペーンなどあるかどうか、狙う必要あるかどうか
わかりません

会計は個別出来そう？割り勘ならペイペイ？＋現金, LINE Pay, Kyash？
わかりません

禁煙席かお店さん自体が禁煙
わかりません

インターネット上に食事をご一緒した情報が公開されることを許容するかどうか
公開で大丈夫なのかな、多分

食事中にスマホをいじることを許容するかどうか
わかりません

食べ物シェア
基本は一人で食べるものは一人でだと思います

**Comment by haibalaryo** [comment]
いつ行くの→4月までの金曜だと具体的には
2/23, 3/15, 3/22, 4/5空いてます。
2/23は祝日ですやけどその前日(22日)も空いてることも付け加えておきます。
4/6以降は未確定かも

食べ物→ホルモン焼き美味しそう！お店提案ありがとうございます。

場所→わたしも船橋都合いいです◎

会計→割り勘のときはPayPay, 現金, LINE Pay, Kyashいけます

**Comment by clarinet758** [comment]
突然ですが今週17日の土曜日夜ってどうですか。おにょんへら個人では土曜日出勤早めに上がりと2つほど用事片付けて18時以降が空き時間です。
それとこれはサシでしょうか。こちらではサシを避けるとかはないのですが、社会の複雑な事情により事前に確認せざるを得なくて申し訳ありませぬ。。。
それとこれも休前日が変則なのですが来週は木曜日も有給で4連休にしているので、水曜日が休前日だったりします。。とはいえ木曜金曜どちらも予定は特にないです。
来週末は少し雨降りっぽいかもです。まだ一週間以上先なので天気予報なんていくらでも変わるでしょうけど。

**Comment by haibalaryo** [comment]
今週17日は新潟にいるためむつかしいです(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)伝えそびれてていっぱいごめんなさい　おしごとおつかれさまです。
メンバーは現時点ではサシのつもりですやけど、他の方も誘うのもありかもですです（かんがえてなかった）
声かけるならしゃも爺さんとかですか？
来週は4連休にされてるんですね。いっぱいいっぱいやすんでください。来週の21日水曜日も空いてます！
https://weathernews.jp/onebox/tenki/chiba/12204/
ウェザーニュースで雨予報なのが気になるかもです。

**Comment by clarinet758** [comment]
githubさんの使い方がいまいちわからないし、本来こういう用途でもなくて。。。。
とりあえずの確認済みや調べてみたことなどは下記の通りでしょうか。

https://github.com/clarinet758/NewYearResolution/blob/funabashi_001/meshi/funabashi.txt

**Comment by haibalaryo** [comment]
ですです。ありがとうございます！

**Comment by clarinet758** [comment]
4月の休前日は6,13,19,26です！！ご確認よろしくお願いします！！

**Comment by haibalaryo** [comment]
連絡ありがとうございます🙇‍♂️
月初が忙しめなのとまだ学校の時間割がわかっていないためこちらのいい感じ™︎な日がお伝えできません💦
4/9までには返答できるので待ってほしいです。。

**Comment by haibalaryo** [comment]
9までに返事するって言ったのに10日になっちゃいました……
直前ですけど大丈夫なら13行きたいです
ほかの挙げてくださった日でも大丈夫です◎

**Comment by clarinet758** [comment]
あっ、ぁっ、ぁっ。。。あの今週は土曜日出勤がなくなってしまったので13日よりも12日のがありがたい感じになっております。
来週以降は金曜日が休前日なのは結構信じていいと思います。

**Comment by haibalaryo** [comment]
なるほどです！12も大丈夫です◎
船橋に着けるのが18時半以降なのですが、ごはん19時〜で大丈夫ですか？

**Comment by clarinet758** [comment]
19時は退勤時間となる見込みです。明日12日の金曜日の20時お待合わせからのごはんはいかがでしょうか。

**Comment by haibalaryo** [comment]
承知しました。金曜20時〜でお願いしたいです！

**Comment by clarinet758** [comment]
うおおおおおり。本日金曜日の20時にお待合わせでお願いします。
店の場所把握できてません。予約は取っておらずです。申し訳ありません。

**Comment by haibalaryo** [comment]
いっぱいありがとうございます！✨
提案してくださったお店( https://www.hotpepper.jp/strJ001224559/ )が良さげだなと思ったのでこちらにしましょうか。
見たところ予約できるのが1番遅くて「20時〜」の枠で、おにょんへらさんが間に合うか気になります。間に合うなら予約してしまおうと思うのですが、どうでしょう？

**Comment by clarinet758** [comment]
20時にお店さん乗り込めるように19:45に船橋駅着可能です。
予約受付間に合いそうでしたらよろしくお願いします。

**Comment by clarinet758** [comment]
南口でお願いします。迷子の事故を避けるために。

**Comment by haibalaryo** [comment]
わかりました⭕️初めてのお店なのでこちらとしても助かります！！

**Comment by haibalaryo** [comment]
無事船橋に行くことができたのでこのissueはcloseという感じですか？たぶん

**Comment by clarinet758** [comment]
はいおつかれさまでした。実施した内容に基づいて予約必須っぽいことと服装注意を追記してmainを更新したはずなのでここは閉じます。
